config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'

  # get '/recepies', to: 'recepies#index'
  # get '/recepies/new', to: 'recepies#new', as: 'new_recepie'
  # post '/recepies', to: 'recepies#create'
  # get  '/recepies/:id/edit', to: 'recepies#edit', as: 'edit_recepie'
  # patch '/recepies/:id', to: 'recepies#update'
  # get '/recepies/:id', to: 'recepies#show', as: 'recepie'
  # delete '/recepies/:id', to:'recepies#destroy'

  resources :recipes


end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recepies
  before_save {self.email = email.downcase}
  validates :chef_name, presence: true, length: {minimum: 2, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
                                    uniqueness: {case_sensitive: false},
                                    format: {with: VALID_EMAIL_REGEX}

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  validates :chef_id, presence: true
  validates :name, presence: true, length:{minimum: 5, maximum: 100}
  validates :summary, presence: true, length:{minimum: 1, maximum: 1000}
  validates :description, presence: true, length:{minimum: 1, maximum: 1000}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper

  def gravatar_for(chef, options = {size: 80})
    gravatar_id  = Digest::MD5::hexdigest(chef.email.downcase)
    size         = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chef_name, class: 'gravatar')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <%= yield %>
  <div class="footer">
    <p>&copy; My Recpies 2015</p>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class ="container">
    <%= link_to "myRecepies", root_path, class: "btn btn-lg btn-success", id: "logo" %>

    <div class="nav_item">
      <%= link_to "link 1", "", class: "btn btn-default btn-warning" %>
    </div>

    <div class="nav_item">
      <%= link_to "link 2", "", class: "btn btn-default btn-warning" %>
    </div>

    <div class="nav_item">
      <%= link_to "link 3", "", class: "btn btn-default btn-warning" %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProfessionalRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/footer' %>

</body>


</html>

app/views/pages/home.html.erb
<div class="jumbotron center home">
  <h1>Welcome to My Recepies App</h1>
  <h2>
    This is the home page of my project.
  </h2>
  <%= link_to 'Sign Up Now', "", class: "btn btn-lg btn-success" %>
</div>


<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View as guest user
    </h3>
    <h2 class="left">
      Browse and view recepies and Sign up later
    </h2>
    <p><%= link_to "Browse Receipe Listings", "", class: "btn btn-warning btn-small"  %></p>
  </div>

  <div class="col-lg-4">
    <h3 class="midrow">
      View as guest user
    </h3>
    <h2 class="left">
      Browse and view recepies and Sign up later
    </h2>
    <p><%= link_to "Browse Receipe Listings", "", class: "btn btn-warning btn-small"  %></p>
  </div>

  <div class="col-lg-4">
    <h3 class="midrow">
      View as guest user
    </h3>
    <h2 class="left">
      Browse and view recepies and Sign up later
    </h2>
    <p><%= link_to "Browse Receipe Listings", recipes_path, class: "btn btn-warning btn-small"  %></p>
  </div>
</div>

app/views/recipes/index.html.erb
<h1>All Recipe</h1>
<hr/>

<% @recipes.each do |recipe| %>
    <div class="row">

      <div class="col-md-2">
        <section class="chef_info center">
          <%= gravatar_for recipe.chef, size: 100 %>
          <h5> Chef Name: <%= recipe.chef.chef_name %> </h5>
        </section>
      </div>

      <div class="col-lg-8 well">
        <h4>
          <%= link_to recipe.name, recipe_path(recipe) %>
        </h4>
        <p>
          <%= recipe.summary %>
        </p>
        <p>
          <span class="quiet">
            <small>
              <%= time_ago_in_words(recipe.created_at) %> ago
            </small>
          </span>
        </p>
      </div>
    </div>
    </hr>
<% end %>

app/views/recipes/show.html.erb
<p>
  <h1>
    <%= @recipe.name %>
  </h1>
</p>



<div class="row">
  <div class="col-md-4 pull-right centet">
    <%= gravatar_for @recipe.chef, size: 200%>
    <p>
      <h5> Brought to you by: <%= @recipe.chef.chef_name %> </h5>
    </p>
  </div>

  <div class="col-md-8">
    <h3> <%= @recipe.summary %> </h3>
    <div class="well">
      <p>
        <strong>Steps:</strong>
      </p>
      <%= @recipe.description %>
    </div>
  </div>
</div>

<h5>
  <%= link_to 'Retrun to Recipes Listing', recipes_path, class: 'btn btn-warning btn-small' %>
</h5>